controller_list:
  - name: fake_ur10_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - UR10__base_to_shoulder_pan_joint
      - UR10__shoulder_pan_to_upper_arm_joint
      - UR10__upper_arm_to_fore_arm_joint
      - UR10__fore_arm_to_wrist_1_joint
      - UR10__wrist_1_to_wrist_2_joint
      - UR10__wrist_2_to_wrist_3_joint
  - name: fake_rg6_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_outer_knuckle_joint
      - right_outer_knuckle_joint
initial:  # Define initial robot poses per group
  - group: ur10_arm
    pose: Folded