ur10_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - UR10__base_to_shoulder_pan_joint
    - UR10__shoulder_pan_to_upper_arm_joint
    - UR10__upper_arm_to_fore_arm_joint
    - UR10__fore_arm_to_wrist_1_joint
    - UR10__wrist_1_to_wrist_2_joint
    - UR10__wrist_2_to_wrist_3_joint
  gains:
    UR10__base_to_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    UR10__shoulder_pan_to_upper_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    UR10__upper_arm_to_fore_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    UR10__fore_arm_to_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    UR10__wrist_1_to_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    UR10__wrist_2_to_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
rg6_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_outer_knuckle_joint
    - right_outer_knuckle_joint
  gains:
    left_outer_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_outer_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1