sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    # point_cloud_topic: /camera/depth/points
    point_cloud_topic: voxel_grid/output
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.2
    padding_scale: 2
    max_update_rate: 100.0
    shape_padding: 0.01
    shape_scale: 0.8
    filtered_cloud_topic: voxel_grid/output